image:
  file: .gitpod.Dockerfile

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - bradlc.vscode-tailwindcss
    - coenraads.bracket-pair-colorizer
    - dsznajder.es7-react-js-snippets
    - zhuangtongfa.material-theme
